"""
crypto_ml_model.py — LightGBM classification for Crypto-Native 1H Strategy.

Target: Predict whether the next 12-hour forward return will be > 0.
Features: 1H indicators generated by `crypto_features.py`.
Evaluation: Expanding window Purged Walk-Forward (1 year chunks).
"""

import sys, os
import numpy as np
import pandas as pd
import lightgbm as lgb
import warnings
import json

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# ═══════════════════════════════════════════════
# PREPARE TARGET & FEATURES
# ═══════════════════════════════════════════════

def prepare_ml_data(features_df, close_panel, horizon=12):
    """
    Given the features DataFrame and the original close panel,
    compute the forward N-hour return target and align them.
    
    Target = 1 if forward return > 0.3% (to overcome fees), else 0.
    """
    print(f"\n🎯 STEP 5: Building Target Variable (Forward {horizon}H Return)...")
    
    # Ensure datetime format for merging
    features_df['date'] = pd.to_datetime(features_df['date'])
    
    # Calculate target from the close panel
    fwd_return = close_panel.shift(-horizon) / close_panel - 1
    
    # Target = 1 if return > 0.3% (30 bps to cover strict CoinDCX 0.118*2 + spread fees)
    target_threshold = 0.003
    target_df = (fwd_return > target_threshold).astype(int)
    
    # Melt target into long format
    target_long = target_df.reset_index().melt(
        id_vars=['index'], var_name='ticker', value_name='target'
    )
    target_long.rename(columns={'index': 'date'}, inplace=True)
    
    # Also attach the raw forward return for metric evaluation
    return_long = fwd_return.reset_index().melt(
        id_vars=['index'], var_name='ticker', value_name='fwd_return'
    )
    return_long.rename(columns={'index': 'date'}, inplace=True)
    
    # Merge Features + Target + Fwd Return
    df = features_df.merge(target_long, on=['date', 'ticker'], how='inner')
    df = df.merge(return_long, on=['date', 'ticker'], how='inner')
    
    # Drop rows where target is NaN (at the very end of the dataset)
    df = df.dropna()
    
    print(f"  ✅ Complete ML Dataset: {len(df):,} rows")
    balance = df['target'].mean() * 100
    print(f"  ⚖️ Target Balance (> {target_threshold*100:.1f}% ret): {balance:.1f}% positive")
    
    return df

# ═══════════════════════════════════════════════
# LIGHTGBM PARAMS & TRAINING
# ═══════════════════════════════════════════════

LGBM_PARAMS = {
    "objective": "binary",
    "metric": "auc",
    "boosting_type": "gbdt",
    "num_leaves": 31,
    "learning_rate": 0.05,
    "feature_fraction": 0.8,
    "bagging_fraction": 0.8,
    "bagging_freq": 5,
    "min_child_samples": 100,   # Prevent extreme overfitting on lower timeframes
    "lambda_l1": 1.5,
    "lambda_l2": 1.5,
    "max_depth": 5,             # Shallower trees for noisy crypto data
    "verbose": -1,
    "n_jobs": -1,
    "seed": 42,
}

def get_feature_cols(df):
    exclude = {"date", "ticker", "target", "fwd_return"}
    return [c for c in df.columns if c not in exclude]

# ═══════════════════════════════════════════════
# PURGED WALK-FORWARD (YEAR BY YEAR chunking)
# ═══════════════════════════════════════════════

def crypto_purged_walk_forward(ml_df, results_dir=None):
    """
    Train LightGBM across time without lookahead bias.
    Since we only have 3-4 years of 1H data, we'll split by 6-month blocks
    or 1-year blocks depending on data size.
    """
    feature_cols = get_feature_cols(ml_df)
    
    print(f"\n🧠 STEP 6: Purged Walk-Forward Training (LightGBM)")
    print(f"  Features: {len(feature_cols)} | Samples: {len(ml_df):,}")
    
    ml_df['year'] = ml_df['date'].dt.year
    ml_df['half'] = np.where(ml_df['date'].dt.month <= 6, 1, 2)
    ml_df['period'] = ml_df['year'].astype(str) + "_H" + ml_df['half'].astype(str)
    
    periods = sorted(ml_df['period'].unique())
    print(f"  Periods detected: {periods}")
    
    # Need at least 2 periods for training before testing
    min_train = 2
    if len(periods) <= min_train:
        print("  ❌ Not enough data blocks for walk-forward. Attempting simple 70/30 split instead...")
        # Fallback implementation for extremely short datasets if needed
        # (Omitted here for brevity, assuming Binance pull succeeds)
    
    test_periods = periods[min_train:]
    
    all_predictions = []
    models = []
    fold_metrics = []
    last_model = None
    
    print(f"  Train start: {periods[0]} | Test start: {test_periods[0]}")
    print(f"  {'─' * 65}")
    
    for test_idx, test_period in enumerate(test_periods):
        # Train on all strictly preceding periods
        train_mask = ml_df['period'].isin(periods[:min_train + test_idx])
        test_mask = ml_df['period'] == test_period
        
        train_df = ml_df[train_mask].copy()
        test_df = ml_df[test_mask].copy()
        
        # Purge: Remove last 24 hours of training data to prevent label leakage
        # (12H target horizon + buffer)
        train_dates = sorted(train_df["date"].unique())
        if len(train_dates) > 24:
            purge_cutoff = pd.to_datetime(train_dates[-24])
            train_df = train_df[train_df["date"] < purge_cutoff]
            
        # Train model
        X_train = train_df[feature_cols].values
        y_train = train_df["target"].values
        train_data = lgb.Dataset(X_train, label=y_train, feature_name=feature_cols, free_raw_data=False)
        
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            model = lgb.train(
                LGBM_PARAMS.copy(),
                train_data,
                num_boost_round=150,  # Lower iterations for smaller blocks
                valid_sets=[train_data],
                callbacks=[lgb.log_evaluation(period=0)],
            )
            
        models.append(model)
        last_model = model
        
        # Predict
        X_test = test_df[feature_cols].values
        test_df["prob"] = model.predict(X_test)
        
        # Evaluate
        pred_positive = test_df["prob"] > 0.55  # Strict confidence threshold
        actual_positive = test_df["target"] == 1
        
        accuracy = (pred_positive == actual_positive).mean() * 100
        precision = actual_positive[pred_positive].mean() * 100 if pred_positive.sum() > 0 else 0
        
        avg_ret_buy = test_df.loc[pred_positive, "fwd_return"].mean() * 100 if pred_positive.sum() > 0 else 0
        
        fold_info = {
            "period": test_period,
            "train_size": len(train_df),
            "test_size": len(test_df),
            "precision": float(round(precision, 1)),
            "buy_signals": int(pred_positive.sum()),
            "avg_fwd_ret": float(round(avg_ret_buy, 2)),
        }
        fold_metrics.append(fold_info)
        
        print(
            f"  {test_period}: "
            f"Train={len(train_df):>6,} | Test={len(test_df):>5,} | "
            f"Prec={precision:>4.1f}% | "
            f"Buys={pred_positive.sum():>4d} | "
            f"AvgRet={avg_ret_buy:>+.2f}%"
        )
        
        all_predictions.append(test_df[["date", "ticker", "prob", "target", "fwd_return"]])
        
    predictions_df = pd.concat(all_predictions, ignore_index=True)
    
    # Feature importance
    if last_model:
        importance = last_model.feature_importance(importance_type="gain")
        feat_imp = sorted(zip(feature_cols, importance), key=lambda x: x[1], reverse=True)
        print(f"\n  🏆 Top Predictive Features (Gain):")
        for name, imp in feat_imp[:5]:
            bar = "█" * max(1, int(imp / max(importance) * 20))
            print(f"     {name:<15s} {bar} {imp:.0f}")
            
    if results_dir:
        os.makedirs(results_dir, exist_ok=True)
        with open(os.path.join(results_dir, "crypto_1h_fold_metrics.json"), "w") as f:
            json.dump(fold_metrics, f, indent=2)
            
    return predictions_df, models, fold_metrics
