"""
fx_ml_model.py — LightGBM classification for Forex Systematic Macro.

Target: Predict whether the next 5-Day forward return will be > 0.
Features: Daily indicators generated by `fx_features.py`.
Evaluation: Expanding window Purged Walk-Forward (1 year chunks).
"""

import sys, os
import numpy as np
import pandas as pd
import lightgbm as lgb
import warnings

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from fx_config import TARGET_HORIZON_DAYS, ENGINE_CONFIG_FX

# ═══════════════════════════════════════════════
# PREPARE TARGET & FEATURES
# ═══════════════════════════════════════════════

def prepare_fx_ml_data(features_df, close_panel):
    """
    Given the features DataFrame and the original close panel,
    compute the forward N-day return target and align them.
    
    Target = 1 if forward return > 0.05% (5 pips on EURUSD) to overcome basic retail spread
    """
    print(f"\n🎯 Building Target Variable (Forward {TARGET_HORIZON_DAYS}D Return)...")
    
    features_df['date'] = pd.to_datetime(features_df['date'])
    
    # Calculate target from the close panel
    fwd_return = close_panel.shift(-TARGET_HORIZON_DAYS) / close_panel - 1
    
    # Spread Threshold: ~5 pips (0.0005) / 1.1000 = ~0.00045 or 0.045%
    # We round strictly to 0.0005 (0.05%) to give the model a realistic hurdle
    target_threshold = 0.0005
    target_df = (fwd_return > target_threshold).astype(int)
    
    # yfinance index name is typically 'Date' not 'index'
    idx_name = target_df.index.name if target_df.index.name else 'index'
    
    # Melt target into long format
    target_long = target_df.reset_index().melt(
        id_vars=[idx_name], var_name='ticker', value_name='target'
    )
    target_long.rename(columns={idx_name: 'date'}, inplace=True)
    
    # Also attach the raw forward return for metric evaluation
    return_long = fwd_return.reset_index().melt(
        id_vars=[idx_name], var_name='ticker', value_name='fwd_return'
    )
    return_long.rename(columns={idx_name: 'date'}, inplace=True)
    
    # Merge Features + Target + Fwd Return
    df = features_df.merge(target_long, on=['date', 'ticker'], how='inner')
    df = df.merge(return_long, on=['date', 'ticker'], how='inner')
    
    # Drop rows where target is NaN (at the very end of the dataset)
    df = df.dropna()
    
    print(f"  ✅ Complete ML Dataset: {len(df):,} rows")
    balance = df['target'].mean() * 100
    print(f"  ⚖️ Target Balance (> {target_threshold*100:.2f}% ret): {balance:.1f}% positive")
    
    return df

# ═══════════════════════════════════════════════
# LIGHTGBM PARAMS & TRAINING
# ═══════════════════════════════════════════════

LGBM_PARAMS = {
    "objective": "binary",
    "metric": "auc",
    "boosting_type": "gbdt",
    "num_leaves": 31,
    "learning_rate": 0.05,
    "feature_fraction": 0.8,
    "bagging_fraction": 0.8,
    "bagging_freq": 5,
    "min_child_samples": 200,   # Prevent overfitting on daily macro data
    "lambda_l1": 2.0,           # Strong L1 regularization to ignore irrelevant features
    "lambda_l2": 2.0,
    "max_depth": 5,             # Shallow trees (prevent memorizing noise)
    "verbose": -1,
    "n_jobs": -1,
    "seed": 42,
}

def get_feature_cols(df):
    exclude = {"date", "ticker", "target", "fwd_return"}
    return [c for c in df.columns if c not in exclude]

# ═══════════════════════════════════════════════
# PURGED WALK-FORWARD (YEAR BY YEAR chunking)
# ═══════════════════════════════════════════════

def fx_purged_walk_forward(ml_df):
    """
    Train LightGBM across time without lookahead bias.
    Unlike crypto 1H data which had thousands of bars, FX 1D has ~250 bars/yr.
    We train in 1-Year expanding blocks to capture multi-year macroeconomic regimes.
    """
    feature_cols = get_feature_cols(ml_df)
    
    print(f"\n🧠 Purged Walk-Forward Training (LightGBM)")
    print(f"  Features: {len(feature_cols)} | Samples: {len(ml_df):,}")
    
    ml_df['year'] = ml_df['date'].dt.year
    periods = sorted(ml_df['year'].unique())
    
    # Need at least 5 years of training before testing macro models
    min_train = 5
    test_periods = periods[min_train:]
    
    all_predictions = []
    models = []
    fold_metrics = []
    last_model = None
    
    print(f"  Train start: {periods[0]} | Test start: {test_periods[0]}")
    print(f"  {'─' * 65}")
    
    for test_idx, test_period in enumerate(test_periods):
        # Train on all strictly preceding periods (Expanding Window)
        train_mask = ml_df['year'].isin(periods[:min_train + test_idx])
        test_mask = ml_df['year'] == test_period
        
        train_df = ml_df[train_mask].copy()
        test_df = ml_df[test_mask].copy()
        
        # Purge: Remove last N days of training data to prevent label leakage
        # N = TARGET_HORIZON_DAYS + buffer
        train_dates = sorted(train_df["date"].unique())
        if len(train_dates) > (TARGET_HORIZON_DAYS + 5):
            purge_cutoff = pd.to_datetime(train_dates[-(TARGET_HORIZON_DAYS + 5)])
            train_df = train_df[train_df["date"] < purge_cutoff]
            
        # Train model
        X_train = train_df[feature_cols].values
        y_train = train_df["target"].values
        train_data = lgb.Dataset(X_train, label=y_train, feature_name=feature_cols, free_raw_data=False)
        
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            model = lgb.train(
                LGBM_PARAMS.copy(),
                train_data,
                num_boost_round=100,  # Lower iterations for macro momentum (prevent overfit)
                valid_sets=[train_data],
                callbacks=[lgb.log_evaluation(period=0)],
            )
            
        models.append(model)
        last_model = model
        
        # Predict
        X_test = test_df[feature_cols].values
        test_df["prob"] = model.predict(X_test)
        
        # Evaluate: Stricter Probability threshold for FX (0.55 instead of 0.50)
        # Because we only want to trade strong cross-sectional imbalances
        pred_positive = test_df["prob"] > 0.55 
        actual_positive = test_df["target"] == 1
        
        precision = actual_positive[pred_positive].mean() * 100 if pred_positive.sum() > 0 else 0
        avg_ret_buy = test_df.loc[pred_positive, "fwd_return"].mean() * 100 if pred_positive.sum() > 0 else 0
        
        fold_info = {
            "period": test_period,
            "train_size": len(train_df),
            "test_size": len(test_df),
            "precision": float(round(precision, 1)),
            "buy_signals": int(pred_positive.sum()),
            "avg_fwd_ret": float(round(avg_ret_buy, 2)),
        }
        fold_metrics.append(fold_info)
        
        print(
            f"  {test_period}: "
            f"Train={len(train_df):>5,} | Test={len(test_df):>4,} | "
            f"Prec={precision:>4.1f}% | "
            f"Buys={pred_positive.sum():>4d} | "
            f"AvgRet={avg_ret_buy:>+.2f}%"
        )
        
        all_predictions.append(test_df[["date", "ticker", "prob", "target", "fwd_return"]])
        
    predictions_df = pd.concat(all_predictions, ignore_index=True)
    
    # Feature importance
    if last_model:
        importance = last_model.feature_importance(importance_type="gain")
        feat_imp = sorted(zip(feature_cols, importance), key=lambda x: x[1], reverse=True)
        print(f"\n  🏆 Top Predictive Features (Gain):")
        for name, imp in feat_imp[:5]:
            bar = "█" * max(1, int(imp / max(importance) * 20))
            print(f"     {name:<15s} {bar} {imp:.0f}")
            
    return predictions_df, models, fold_metrics
